### ISSUE TITLE
Unable to import pymeos (conda installation)

### ISSUE THREAD

**Issue by mitirmizi** [MobilityDB/PyMEOS#45] opened 2024-04-05 15:04 UTC
I created a new virtual environment and installed Pymeos using: `conda install conda-forge::pymeos`. Conda Page for pymeos: https://anaconda.org/conda-forge/pymeos.

## Issue:
When I import pymeos I get the following error:
```python-REPL
>>> import pymeos as pm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/teemo/anaconda3/envs/pym2/lib/python3.12/site-packages/pymeos/_init_.py", line 1, in <module>
    from .aggregators import *
  File "/home/teemo/anaconda3/envs/pym2/lib/python3.12/site-packages/pymeos/aggregators/_init_.py", line 1, in <module>
    from .bool_aggregators import *
  File "/home/teemo/anaconda3/envs/pym2/lib/python3.12/site-packages/pymeos/aggregators/bool_aggregators.py", line 1, in <module>
    from pymeos_cffi import *
  File "/home/teemo/anaconda3/envs/pym2/lib/python3.12/site-packages/pymeos_cffi/_init_.py", line 1, in <module>
    from .functions import *
  File "/home/teemo/anaconda3/envs/pym2/lib/python3.12/site-packages/pymeos_cffi/functions.py", line 5, in <module>
    import _meos_cffi
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```

**Comment by Diviloper** [comment] 2024-04-15 17:04
I'm unable to reproduce this issue. When installing `pymeos` in a clean environment (using the [miniconda docker image](https://hub.docker.com/r/continuumio/miniconda3)), `gsl` gets installed when installing `pymeos`, and it seems to be working properly.
Could you provide more details of your environment to try and reproduce your issue?

**Comment by mitirmizi** [comment] 2024-04-21 03:39
When I install it with Anaconda version:  22.9.0. I get the following (image below). I though initially that this was due to me using python 3.12. But I got the same behavior with python 3.11 and 3.10 as can be seen below.

![image](https://github.com/MobilityDB/PyMEOS/assets/22791921/5d97697a-20fc-4114-b4f4-620f872f6e41)

**Comment by Diviloper** [comment] 2024-04-21 06:43
I've been able to reproduce the issue. It seems like a dependency mismatch caused by the different conda channels and their priorities. When installing `pymeos` through `conda-forge`, conda is getting some packages from the `defaults` channel and others from the `conda-forge` channel, when ideally, it should get them all from the latter.  
To fix this, just run this to set `conda-forge` as the first option and try to install again:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
These instructions are indicated in the [feedstock repo](https://github.com/conda-forge/pymeos-feedstock), but missing from the [PyMEOS documentation](https://pymeos.readthedocs.io/en/latest/src/installation.html#installation-using-conda).  
I will add them there to avoid these problems in the future.

Please confirm whether this solved the issue.

**Comment by Diviloper** [comment] 2024-04-21 07:03
The documentation has been updated in #51, which will be merged as soon as this issue is closed

**Comment by mitirmizi** [comment] 2024-04-21 10:19
@Diviloper you were correct about this going back to my installations I see that indeed previously I ` conda install conda-forge::pymeos` install packages from different channels. 
Packages installed previously:
```
The following NEW packages will be INSTALLED:

  c-ares             conda-forge/linux-64::c-ares-1.28.1-hd590300_0 None
  cffi               pkgs/main/linux-64::cffi-1.16.0-py310h5eee18b_0 None
  geos               conda-forge/linux-64::geos-3.12.1-h59595ed_0 None
  gsl                pkgs/main/linux-64::gsl-2.7.1-h6e86dc7_1 None
  json-c             conda-forge/linux-64::json-c-0.17-h7ab15ed_0 None
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 None
  krb5               conda-forge/linux-64::krb5-1.21.2-h659d440_0 None
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0 None
  libblas            conda-forge/linux-64::libblas-3.9.0-16_linux64_openblas None
  libcblas           conda-forge/linux-64::libcblas-3.9.0-16_linux64_openblas None
  libcurl            conda-forge/linux-64::libcurl-8.7.1-hca28451_0 None
  libdeflate         conda-forge/linux-64::libdeflate-1.20-hd590300_0 None
  libedit            pkgs/main/linux-64::libedit-3.1.20230828-h5eee18b_0 None
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1 None
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1 None
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1 None
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.0.0-hd590300_1 None
  liblapack          conda-forge/linux-64::liblapack-3.9.0-16_linux64_openblas None
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 None
  libopenblas        pkgs/main/linux-64::libopenblas-0.3.21-h043d6bf_0 None
  libpq              conda-forge/linux-64::libpq-16.2-h33b98f1_1 None
  libsqlite          conda-forge/linux-64::libsqlite-3.45.3-h2797004_0 None
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 None
  libtiff            conda-forge/linux-64::libtiff-4.6.0-h1dd3fc0_3 None
  libwebp-base       pkgs/main/linux-64::libwebp-base-1.3.2-h5eee18b_0 None
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 None
  llvm-openmp        pkgs/main/linux-64::llvm-openmp-14.0.6-h9e868ea_0 None
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.4-h6a678d5_0 None
  meos               conda-forge/linux-64::meos-1.1.1-h8518783_0 None
  numpy              conda-forge/linux-64::numpy-1.26.4-py310hb13e2d6_0 None
  proj               conda-forge/linux-64::proj-9.4.0-h1d62c97_0 None
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0 None
  pymeos             conda-forge/noarch::pymeos-1.1.3-pyhd8ed1ab_0 None
  pymeos-cffi        conda-forge/linux-64::pymeos-cffi-1.1.1-py310h2372a71_0 None
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0 None
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310 None
  shapely            conda-forge/linux-64::shapely-2.0.4-py310hc3e127f_0 None
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1 None
  zstd               pkgs/main/linux-64::zstd-1.5.5-hc292b87_0 None
```
But after this fix: 
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
Packages INSTALLED were:
```
  c-ares             conda-forge/linux-64::c-ares-1.28.1-hd590300_0 None
  cffi               conda-forge/linux-64::cffi-1.16.0-py310h2fee648_0 None
  geos               conda-forge/linux-64::geos-3.12.1-h59595ed_0 None
  gsl                conda-forge/linux-64::gsl-2.7-he838d99_0 None
  json-c             conda-forge/linux-64::json-c-0.17-h7ab15ed_0 None
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 None
  krb5               conda-forge/linux-64::krb5-1.21.2-h659d440_0 None
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0 None
  libblas            conda-forge/linux-64::libblas-3.9.0-22_linux64_openblas None
  libcblas           conda-forge/linux-64::libcblas-3.9.0-22_linux64_openblas None
  libcurl            conda-forge/linux-64::libcurl-8.7.1-hca28451_0 None
  libdeflate         conda-forge/linux-64::libdeflate-1.20-hd590300_0 None
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 None
  libev              conda-forge/linux-64::libev-4.33-hd590300_2 None
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-13.2.0-h69a702a_5 None
  libgfortran5       conda-forge/linux-64::libgfortran5-13.2.0-ha4646dd_5 None
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.0.0-hd590300_1 None
  liblapack          conda-forge/linux-64::liblapack-3.9.0-22_linux64_openblas None
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 None
  libopenblas        conda-forge/linux-64::libopenblas-0.3.27-pthreads_h413a1c8_0 None
  libpq              conda-forge/linux-64::libpq-16.2-h33b98f1_1 None
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 None
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_5 None
  libtiff            conda-forge/linux-64::libtiff-4.6.0-h1dd3fc0_3 None
  libwebp-base       conda-forge/linux-64::libwebp-base-1.4.0-hd590300_0 None
  meos               conda-forge/linux-64::meos-1.1.1-h8518783_0 None
  numpy              conda-forge/linux-64::numpy-1.26.4-py310hb13e2d6_0 None
  proj               conda-forge/linux-64::proj-9.4.0-h1d62c97_0 None
  pycparser          conda-forge/noarch::pycparser-2.22-pyhd8ed1ab_0 None
  pymeos             conda-forge/noarch::pymeos-1.1.3-pyhd8ed1ab_0 None
  pymeos-cffi        conda-forge/linux-64::pymeos-cffi-1.1.1-py310h2372a71_0 None
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 None
  python_abi         conda-forge/linux-64::python_abi-3.10-4_cp310 None
  shapely            conda-forge/linux-64::shapely-2.0.4-py310hc3e127f_0 None
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 None
  sqlite             conda-forge/linux-64::sqlite-3.45.3-h2c6b66d_0 None
  zstd               conda-forge/linux-64::zstd-1.5.5-hfc55251_0 None
  ```

This fixed the issue. Now I can successfully import pymeos.

**Closed** 2024-04-21 10:20 UTC
Labels: documentation
